const express = require('express');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { requireAccess } = require('../middleware/require-access');

const router = express.Router();
const FILE = process.env.RECRUITMENT_FILE_PATH || (process.env.NODE_ENV === 'staging' ? '/data-staging/recruitment.json' : path.resolve(__dirname, '../../data/recruitment.json'));
const STAGES = new Set(['novo', 'triagem', 'contato', 'entrevista', 'aprovado', 'recusado']);
function load() { try { const data = JSON.parse(fs.readFileSync(FILE, 'utf8')); return data && typeof data === 'object' ? data : { vacancies: [], candidates: [] }; } catch { return { vacancies: [], candidates: [] }; } }
function save(data) { fs.mkdirSync(path.dirname(FILE), { recursive: true }); fs.writeFileSync(FILE, `${JSON.stringify(data, null, 2)}\n`, 'utf8'); }
function slug(value) { return String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48); }
function vacancyFor(data, user) { let item = data.vacancies.find((v) => v.organizationId === user.organizationId); if (!item) { item = { organizationId: user.organizationId, slug: `${slug(user.organization?.name || 'corretora')}-${user.organizationId.slice(0, 6)}`, companyName: user.organization?.name || 'Corretora', logo: '', title: 'Consultor de Planos de Saúde', headline: 'Venha construir sua carreira conosco', description: '', requirements: '', benefits: '', workModel: 'Presencial', location: '', active: false, updatedAt: new Date().toISOString() }; data.vacancies.push(item); } return item; }

router.get('/api/supervisor/recruitment', requireAccess('supervisor'), (req, res) => { const data = load(); const vacancy = vacancyFor(data, req.accessUser); save(data); const candidates = data.candidates.filter((c) => c.organizationId === req.accessUser.organizationId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); res.json({ ok: true, vacancy, candidates }); });
router.patch('/api/supervisor/recruitment/vacancy', requireAccess('supervisor'), (req, res) => { const data = load(); const item = vacancyFor(data, req.accessUser); const body = req.body || {}; ['title','headline','description','requirements','benefits','workModel','location','companyName'].forEach((key) => { if (key in body) item[key] = String(body[key] || '').trim().slice(0, key === 'title' ? 120 : 5000); }); if ('logo' in body) item.logo = String(body.logo || '').startsWith('data:image/') ? String(body.logo).slice(0, 1800000) : ''; if ('active' in body) item.active = Boolean(body.active); if (body.slug) item.slug = `${slug(body.slug)}-${req.accessUser.organizationId.slice(0, 6)}`; item.updatedAt = new Date().toISOString(); save(data); res.json({ ok: true, vacancy: item }); });
router.patch('/api/supervisor/recruitment/candidates/:id', requireAccess('supervisor'), (req, res) => { const data = load(); const item = data.candidates.find((c) => c.id === req.params.id && c.organizationId === req.accessUser.organizationId); if (!item) return res.status(404).json({ ok: false, error: 'Candidato não encontrado.' }); if (req.body.stage) { if (!STAGES.has(req.body.stage)) return res.status(400).json({ ok: false, error: 'Etapa inválida.' }); item.stage = req.body.stage; } if ('notes' in req.body) item.notes = String(req.body.notes || '').trim().slice(0, 3000); if ('hirePending' in req.body) item.hirePending = Boolean(req.body.hirePending); if ('hiredUserId' in req.body) item.hiredUserId = String(req.body.hiredUserId || ''); if (req.body.seen) item.seenAt ||= new Date().toISOString(); item.updatedAt = new Date().toISOString(); save(data); res.json({ ok: true, candidate: item }); });
router.delete('/api/supervisor/recruitment/candidates/:id', requireAccess('supervisor'), (req, res) => { const data = load(); const index = data.candidates.findIndex((c) => c.id === req.params.id && c.organizationId === req.accessUser.organizationId); if (index < 0) return res.status(404).json({ ok: false, error: 'Candidato não encontrado.' }); if (data.candidates[index].stage !== 'recusado') return res.status(409).json({ ok: false, error: 'Somente candidatos recusados podem ser excluídos.' }); data.candidates.splice(index, 1); save(data); res.json({ ok: true }); });
router.post('/api/supervisor/recruitment/candidates/seen', requireAccess('supervisor'), (req, res) => { const data = load(); const now = new Date().toISOString(); data.candidates.filter((c) => c.organizationId === req.accessUser.organizationId && !c.seenAt).forEach((c) => { c.seenAt = now; }); save(data); res.json({ ok: true }); });

router.get('/api/public/vacancies/:slug', (req, res) => { const item = load().vacancies.find((v) => v.slug === req.params.slug && v.active); if (!item) return res.status(404).json({ ok: false, error: 'Vaga indisponível.' }); const { organizationId, ...vacancy } = item; res.json({ ok: true, vacancy }); });
router.post('/api/public/vacancies/:slug/apply', (req, res) => { const data = load(); const vacancy = data.vacancies.find((v) => v.slug === req.params.slug && v.active); if (!vacancy) return res.status(404).json({ ok: false, error: 'Vaga indisponível.' }); if (req.body?.website) return res.status(201).json({ ok: true }); const name = String(req.body?.name || '').trim(), phone = String(req.body?.phone || '').replace(/\D/g, ''), email = String(req.body?.email || '').trim(); if (name.length < 2 || phone.length < 10) return res.status(400).json({ ok: false, error: 'Informe nome e WhatsApp válidos.' }); const recent = data.candidates.find((c) => c.vacancySlug === vacancy.slug && c.phone === phone && Date.now() - Date.parse(c.createdAt) < 10 * 60 * 1000); if (recent) return res.status(200).json({ ok: true, candidateId: recent.id, duplicate: true }); const now = new Date().toISOString(); const item = { id: crypto.randomUUID(), organizationId: vacancy.organizationId, vacancySlug: vacancy.slug, name, phone, email, city: String(req.body?.city || '').trim(), experience: String(req.body?.experience || '').trim(), resumeUrl: String(req.body?.resumeUrl || '').trim(), message: String(req.body?.message || '').trim(), stage: 'novo', notes: '', seenAt: null, hirePending: false, hiredUserId: '', createdAt: now, updatedAt: now }; data.candidates.push(item); save(data); res.status(201).json({ ok: true, candidateId: item.id }); });

module.exports = router;
