const express = require('express');
const path = require('path');
const requireAdmin = require('../middleware/require-admin');
const { requireAccess } = require('../middleware/require-access');
const supabase = require('../database/supabase');
const store = require('../services/training-store');
const { sendTrainingNotificationEmail } = require('../services/access-email');

const router = express.Router();
const baseDataDir = process.env.NODE_ENV === 'staging' ? '/data-staging' : process.env.NODE_ENV === 'production' ? '/data' : path.resolve(__dirname, '../../data');
const TRAININGS_FILE = process.env.TRAININGS_FILE_PATH || path.join(baseDataDir, 'trainings.json');
const PROGRESS_FILE = process.env.TRAINING_PROGRESS_FILE_PATH || path.join(baseDataDir, 'training-progress.json');
const prepare = () => store.ensureLegacyImported(TRAININGS_FILE, PROGRESS_FILE);

function youtubeId(url) { try { const parsed = new URL(url); if (parsed.hostname.includes('youtu.be')) return parsed.pathname.slice(1).split('/')[0]; if (parsed.hostname.includes('youtube.com')) return parsed.searchParams.get('v') || parsed.pathname.split('/').filter(Boolean).pop(); } catch {} return ''; }
function payload(body, current = {}) { const title = String(body.title ?? current.title ?? '').trim(), url = String(body.url ?? current.url ?? '').trim(); const track = String(body.track ?? current.track ?? 'Geral').trim() || 'Geral', description = String(body.description ?? current.description ?? '').trim(); const stars = Math.max(0, Math.min(5, Number(body.stars ?? current.stars ?? 0) || 0)), order = Math.max(0, Number(body.order ?? current.order ?? 0) || 0); if (title.length < 2) throw Object.assign(new Error('Informe o nome do treinamento.'), { statusCode: 400 }); if (!youtubeId(url)) throw Object.assign(new Error('Informe um link válido do YouTube.'), { statusCode: 400 }); return { ...current, title, url, youtubeId: youtubeId(url), track, description, stars, order, active: body.active === undefined ? current.active !== false : Boolean(body.active) }; }
const origin = (item) => item.ownerType || 'admin';
const sorted = (items) => items.sort((a, b) => String(a.track).localeCompare(String(b.track)) || a.order - b.order || String(a.title).localeCompare(String(b.title)));
const visibleTo = (item, user) => item.active !== false && (origin(item) === 'admin' || (origin(item) === 'supervisor' && item.organizationId === user.organizationId));
function publicTraining(item, progress) { const own = progress.find((entry) => entry.trainingId === item.id); return { ...item, ownerType: origin(item), progress: own ? { percent: own.percent, status: own.status, lastViewedAt: own.lastViewedAt } : { percent: 0, status: 'not_started', lastViewedAt: null } }; }
async function usersFor(query) { const { data, error } = await query; if (error) throw error; return data || []; }
async function notify(training, users, publisherName) { const recipients = users.filter((user) => user.email); const enabled = process.env.NODE_ENV !== 'staging' || String(process.env.TRAINING_EMAIL_NOTIFICATIONS_ENABLED || '').toLowerCase() === 'true'; if (!enabled) return { recipients: recipients.length, sent: 0, failed: 0, suppressed: true }; const results = await Promise.allSettled(recipients.map((user) => sendTrainingNotificationEmail({ email: user.email, name: user.name, trainingTitle: training.title, track: training.track, publisherName, organizationName: user.organizations?.name || 'Lungo Corretores' }))); return { recipients: recipients.length, sent: results.filter((item) => item.status === 'fulfilled').length, failed: results.filter((item) => item.status === 'rejected').length }; }

router.get('/api/training-center', requireAccess(['supervisor', 'broker']), async (req, res, next) => { try { await prepare(); const [trainings, progress] = await Promise.all([store.listTrainings(), store.listProgress({ userId: req.accessUser.id })]); res.json({ ok: true, trainings: sorted(trainings.filter((item) => visibleTo(item, req.accessUser)).map((item) => publicTraining(item, progress))) }); } catch (error) { next(error); } });
router.post('/api/training-center/:id/progress', requireAccess(['supervisor', 'broker']), async (req, res, next) => { try { await prepare(); const training = await store.getTraining(req.params.id); if (!training || !visibleTo(training, req.accessUser)) return res.status(404).json({ ok: false, error: 'Treinamento não encontrado.' }); const duration = Math.max(0, Math.min(86400, Number(req.body?.duration) || 0)), currentTime = Math.max(0, Math.min(duration, Number(req.body?.currentTime) || 0)), delta = Math.max(0, Math.min(15, Number(req.body?.watchedSecondsDelta) || 0)); if (!duration) return res.status(400).json({ ok: false, error: 'Duração inválida.' }); const previous = (await store.listProgress({ trainingId: training.id, userId: req.accessUser.id }))[0]; const now = new Date().toISOString(); const item = previous || { trainingId: training.id, userId: req.accessUser.id, userName: req.accessUser.name, userEmail: req.accessUser.email, userRole: req.accessUser.role, organizationId: req.accessUser.organizationId, organizationName: req.accessUser.organization?.name || '', watchedSeconds: 0, currentTime: 0, duration, percent: 0, status: 'in_progress', startedAt: now, completedAt: null }; item.duration = Math.max(Number(item.duration || 0), duration); item.watchedSeconds = Math.min(item.duration, Number(item.watchedSeconds || 0) + delta); item.currentTime = Math.max(Number(item.currentTime || 0), currentTime); item.lastViewedAt = now; item.percent = Math.max(Number(item.percent || 0), Math.min(100, Math.round((item.currentTime / item.duration) * 100))); item.status = item.percent >= 90 ? 'completed' : 'in_progress'; if (item.status === 'completed' && !item.completedAt) item.completedAt = now; const progress = await store.saveProgress(item); res.json({ ok: true, progress: { percent: progress.percent, status: progress.status, lastViewedAt: progress.lastViewedAt } }); } catch (error) { next(error); } });

router.get('/api/training-center/supervisor/manage', requireAccess('supervisor'), async (req, res, next) => { try { await prepare(); res.json({ ok: true, trainings: sorted((await store.listTrainings()).filter((item) => origin(item) === 'supervisor' && item.organizationId === req.accessUser.organizationId)) }); } catch (error) { next(error); } });
router.post('/api/training-center/supervisor', requireAccess('supervisor'), async (req, res, next) => { try { await prepare(); const item = await store.createTraining({ ...payload(req.body), ownerType: 'supervisor', ownerUserId: req.accessUser.id, ownerName: req.accessUser.name, organizationId: req.accessUser.organizationId }); const users = await usersFor(supabase.from('users').select('id,name,email,role,organization_id,organizations!users_organization_id_fkey(name)').eq('organization_id', req.accessUser.organizationId).eq('role', 'broker').eq('status', 'active')); let emailDelivery; try { emailDelivery = await notify(item, users, req.accessUser.name); } catch (error) { emailDelivery = { recipients: users.length, sent: 0, failed: users.length, error: error.message }; } res.status(201).json({ ok: true, training: item, emailDelivery }); } catch (error) { next(error); } });
router.patch('/api/training-center/supervisor/:id', requireAccess('supervisor'), async (req, res, next) => { try { await prepare(); const current = await store.getTraining(req.params.id); if (!current || origin(current) !== 'supervisor' || current.organizationId !== req.accessUser.organizationId) return res.status(404).json({ ok: false, error: 'Treinamento não encontrado.' }); res.json({ ok: true, training: await store.updateTraining(req.params.id, { ...payload(req.body, current), updatedAt: new Date().toISOString() }) }); } catch (error) { next(error); } });
router.delete('/api/training-center/supervisor/:id', requireAccess('supervisor'), async (req, res, next) => { try { await prepare(); const current = await store.getTraining(req.params.id); if (!current || origin(current) !== 'supervisor' || current.organizationId !== req.accessUser.organizationId) return res.status(404).json({ ok: false, error: 'Treinamento não encontrado.' }); await store.deleteTraining(req.params.id); res.json({ ok: true }); } catch (error) { next(error); } });

async function metricsFor(training, organizationId = null) { const progress = await store.listProgress({ trainingId: training.id, ...(organizationId ? { organizationId, userRole: 'broker' } : {}) }); const ids = [...new Set(progress.map((item) => item.userId))]; let userMap = new Map(); if (ids.length) { const { data } = await supabase.from('users').select('id,name,email,role,organizations!users_organization_id_fkey(name)').in('id', ids); userMap = new Map((data || []).map((user) => [user.id, user])); } return progress.map((item) => { const user = userMap.get(item.userId); return { ...item, userName: user?.name || item.userName, userEmail: user?.email || item.userEmail, userRole: user?.role || item.userRole, organizationName: user?.organizations?.name || item.organizationName }; }); }
router.get('/api/training-center/supervisor/:id/metrics', requireAccess('supervisor'), async (req, res, next) => { try { await prepare(); const training = await store.getTraining(req.params.id); if (!training || !(origin(training) === 'admin' || training.organizationId === req.accessUser.organizationId)) return res.status(404).json({ ok: false, error: 'Treinamento não encontrado.' }); res.json({ ok: true, training: { id: training.id, title: training.title }, viewers: await metricsFor(training, req.accessUser.organizationId) }); } catch (error) { next(error); } });

router.get('/api/admin/training-center', requireAdmin, async (_req, res, next) => { try { await prepare(); res.json({ ok: true, trainings: (await store.listTrainings()).filter((item) => origin(item) === 'admin') }); } catch (error) { next(error); } });
router.post('/api/admin/training-center', requireAdmin, async (req, res, next) => { try { await prepare(); const item = await store.createTraining({ ...payload(req.body), ownerType: 'admin' }); const users = await usersFor(supabase.from('users').select('id,name,email,role,organization_id,organizations!users_organization_id_fkey(name)').in('role', ['supervisor', 'broker']).eq('status', 'active')); let emailDelivery; try { emailDelivery = await notify(item, users, 'Lungo Corretores'); } catch (error) { emailDelivery = { recipients: users.length, sent: 0, failed: users.length, error: error.message }; } res.status(201).json({ ok: true, training: item, emailDelivery }); } catch (error) { next(error); } });
router.patch('/api/admin/training-center/:id', requireAdmin, async (req, res, next) => { try { await prepare(); const current = await store.getTraining(req.params.id); if (!current || origin(current) !== 'admin') return res.status(404).json({ ok: false, error: 'Treinamento não encontrado.' }); res.json({ ok: true, training: await store.updateTraining(req.params.id, { ...payload(req.body, current), ownerType: 'admin', organizationId: null, updatedAt: new Date().toISOString() }) }); } catch (error) { next(error); } });
router.delete('/api/admin/training-center/:id', requireAdmin, async (req, res, next) => { try { await prepare(); const current = await store.getTraining(req.params.id); if (!current || origin(current) !== 'admin') return res.status(404).json({ ok: false, error: 'Treinamento não encontrado.' }); await store.deleteTraining(req.params.id); res.json({ ok: true }); } catch (error) { next(error); } });
router.get('/api/admin/training-center/:id/metrics', requireAdmin, async (req, res, next) => { try { await prepare(); const training = await store.getTraining(req.params.id); if (!training || origin(training) !== 'admin') return res.status(404).json({ ok: false, error: 'Treinamento não encontrado.' }); res.json({ ok: true, training: { id: training.id, title: training.title }, viewers: await metricsFor(training) }); } catch (error) { next(error); } });

module.exports = router;
