const express = require('express');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const requireAdmin = require('../middleware/require-admin');
const { requireAccess } = require('../middleware/require-access');
const supabase = require('../database/supabase');
const { sendTrainingNotificationEmail } = require('../services/access-email');

const router = express.Router();
const baseDataDir = process.env.NODE_ENV === 'staging' ? '/data-staging' : process.env.NODE_ENV === 'production' ? '/data' : path.resolve(__dirname, '../../data');
const TRAININGS_FILE = process.env.TRAININGS_FILE_PATH || (process.env.NODE_ENV === 'staging' ? '/data-staging/trainings.json' : path.resolve(__dirname, '../../data/trainings.json'));
const PROGRESS_FILE = process.env.TRAINING_PROGRESS_FILE_PATH || path.join(baseDataDir, 'training-progress.json');

function loadFile(file) { try { const value = JSON.parse(fs.readFileSync(file, 'utf8')); return Array.isArray(value) ? value : []; } catch { return []; } }
function saveFile(file, items) { fs.mkdirSync(path.dirname(file), { recursive: true }); const temporary = `${file}.${process.pid}.tmp`; fs.writeFileSync(temporary, `${JSON.stringify(items, null, 2)}\n`, 'utf8'); fs.renameSync(temporary, file); }
const load = () => loadFile(TRAININGS_FILE), save = (items) => saveFile(TRAININGS_FILE, items);
const loadProgress = () => loadFile(PROGRESS_FILE), saveProgress = (items) => saveFile(PROGRESS_FILE, items);

function youtubeId(url) { try { const parsed = new URL(url); if (parsed.hostname.includes('youtu.be')) return parsed.pathname.slice(1).split('/')[0]; if (parsed.hostname.includes('youtube.com')) return parsed.searchParams.get('v') || parsed.pathname.split('/').filter(Boolean).pop(); } catch {} return ''; }
function payload(body, current = {}) {
  const title = String(body.title ?? current.title ?? '').trim(), url = String(body.url ?? current.url ?? '').trim();
  const track = String(body.track ?? current.track ?? 'Geral').trim() || 'Geral', description = String(body.description ?? current.description ?? '').trim();
  const stars = Math.max(0, Math.min(5, Number(body.stars ?? current.stars ?? 0) || 0)), order = Math.max(0, Number(body.order ?? current.order ?? 0) || 0);
  if (title.length < 2) throw Object.assign(new Error('Informe o nome do treinamento.'), { statusCode: 400 });
  if (!youtubeId(url)) throw Object.assign(new Error('Informe um link valido do YouTube.'), { statusCode: 400 });
  return { ...current, title, url, youtubeId: youtubeId(url), track, description, stars, order, active: body.active === undefined ? current.active !== false : Boolean(body.active) };
}
const origin = (item) => item.ownerType || 'admin';
const sorted = (items) => items.sort((a, b) => String(a.track).localeCompare(String(b.track)) || a.order - b.order || String(a.title).localeCompare(String(b.title)));
const visibleTo = (item, user) => item.active !== false && (origin(item) === 'admin' || (origin(item) === 'supervisor' && item.organizationId === user.organizationId));
function publicTraining(item, progress) { const own = progress.find((entry) => entry.trainingId === item.id); return { ...item, ownerType: origin(item), progress: own ? { percent: own.percent, status: own.status, lastViewedAt: own.lastViewedAt } : { percent: 0, status: 'not_started', lastViewedAt: null } }; }
async function usersFor(query) { const { data, error } = await query; if (error) throw error; return data || []; }
async function notify(training, users, publisherName) { const recipients = users.filter((user) => user.email); const enabled = process.env.NODE_ENV !== 'staging' || String(process.env.TRAINING_EMAIL_NOTIFICATIONS_ENABLED || '').toLowerCase() === 'true'; if (!enabled) return { recipients: recipients.length, sent: 0, failed: 0, suppressed: true }; const results = await Promise.allSettled(recipients.map((user) => sendTrainingNotificationEmail({ email: user.email, name: user.name, trainingTitle: training.title, track: training.track, publisherName, organizationName: user.organizations?.name || 'Lungo Corretores' }))); return { recipients: recipients.length, sent: results.filter((item) => item.status === 'fulfilled').length, failed: results.filter((item) => item.status === 'rejected').length }; }

router.get('/api/training-center', requireAccess(['supervisor', 'broker']), (req, res) => { const progress = loadProgress().filter((item) => item.userId === req.accessUser.id); res.json({ ok: true, trainings: sorted(load().filter((item) => visibleTo(item, req.accessUser)).map((item) => publicTraining(item, progress))) }); });
router.post('/api/training-center/:id/progress', requireAccess(['supervisor', 'broker']), (req, res) => {
  const training = load().find((item) => item.id === req.params.id && visibleTo(item, req.accessUser)); if (!training) return res.status(404).json({ ok: false, error: 'Treinamento nao encontrado.' });
  const duration = Math.max(0, Math.min(86400, Number(req.body?.duration) || 0)), currentTime = Math.max(0, Math.min(duration, Number(req.body?.currentTime) || 0)), delta = Math.max(0, Math.min(15, Number(req.body?.watchedSecondsDelta) || 0));
  if (!duration) return res.status(400).json({ ok: false, error: 'Duracao invalida.' });
  const items = loadProgress(), now = new Date().toISOString(); let item = items.find((entry) => entry.trainingId === training.id && entry.userId === req.accessUser.id);
  if (!item) { item = { id: crypto.randomUUID(), trainingId: training.id, userId: req.accessUser.id, userName: req.accessUser.name, userEmail: req.accessUser.email, userRole: req.accessUser.role, organizationId: req.accessUser.organizationId, organizationName: req.accessUser.organization?.name || '', watchedSeconds: 0, duration, percent: 0, status: 'in_progress', startedAt: now, lastViewedAt: now, completedAt: null }; items.push(item); }
  item.duration = Math.max(Number(item.duration || 0), duration); item.watchedSeconds = Math.min(item.duration, Number(item.watchedSeconds || 0) + delta); item.currentTime = currentTime; item.lastViewedAt = now; item.percent = Math.min(100, Math.round((item.watchedSeconds / item.duration) * 100)); item.status = item.percent >= 90 ? 'completed' : 'in_progress'; if (item.status === 'completed' && !item.completedAt) item.completedAt = now;
  saveProgress(items); res.json({ ok: true, progress: { percent: item.percent, status: item.status, lastViewedAt: item.lastViewedAt } });
});

router.get('/api/training-center/supervisor/manage', requireAccess('supervisor'), (req, res) => res.json({ ok: true, trainings: sorted(load().filter((item) => origin(item) === 'supervisor' && item.organizationId === req.accessUser.organizationId)) }));
router.post('/api/training-center/supervisor', requireAccess('supervisor'), async (req, res, next) => { try { const items = load(), now = new Date().toISOString(), item = payload(req.body); Object.assign(item, { id: crypto.randomUUID(), ownerType: 'supervisor', ownerUserId: req.accessUser.id, ownerName: req.accessUser.name, organizationId: req.accessUser.organizationId, createdAt: now, updatedAt: now }); items.push(item); save(items); const users = await usersFor(supabase.from('users').select('id,name,email,role,organization_id,organizations!users_organization_id_fkey(name)').eq('organization_id', req.accessUser.organizationId).eq('role', 'broker').eq('status', 'active')); let emailDelivery; try { emailDelivery = await notify(item, users, req.accessUser.name); } catch (error) { emailDelivery = { recipients: users.length, sent: 0, failed: users.length, error: error.message }; } res.status(201).json({ ok: true, training: item, emailDelivery }); } catch (error) { next(error); } });
router.patch('/api/training-center/supervisor/:id', requireAccess('supervisor'), (req, res, next) => { try { const items = load(), index = items.findIndex((item) => item.id === req.params.id && origin(item) === 'supervisor' && item.organizationId === req.accessUser.organizationId); if (index < 0) return res.status(404).json({ ok: false, error: 'Treinamento nao encontrado.' }); items[index] = { ...payload(req.body, items[index]), updatedAt: new Date().ISOString() }; save(items); res.json({ ok: true, training: items[index] }); } catch (error) { next(error); } });
router.delete('/api/training-center/supervisor/:id', requireAccess('supervisor'), (req, res) => { const items = load(), next = items.filter((item) => !(item.id === req.params.id && origin(item) === 'supervisor' && item.organizationId === req.accessUser.organizationId)); if (next.length === items.length) return res.status(404).json({ ok: false, error: 'Treinamento nao encontrado.' }); save(next); res.json({ ok: true }); });

async function metricsFor(training, organizationId = null) { let progress = loadProgress().filter((item) => item.trainingId === training.id); if (organizationId) progress = progress.filter((item) => item.organizationId === organizationId && item.userRole === 'broker'); const ids = [...new Set(progress.map((item) => item.userId))]; let userMap = new Map(); if (ids.length) { const { data } = await supabase.from('users').select('id,name,email,role,organizations!users_organization_id_fkey(name)').in('id', ids); userMap = new Map((data || []).map((user) => [user.id, user])); } return progress.map((item) => { const user = userMap.get(item.userId); return { ...item, userName: user?.name || item.userName, userEmail: user?.email || item.userEmail, userRole: user?.role || item.userRole, organizationName: user?.organizations?.name || item.organizationName }; }).sort((a, b) => String(b.lastViewedAt).localeCompare(String(a.lastViewedAt))); }
router.get('/api/training-center/supervisor/:id/metrics', requireAccess('supervisor'), async (req, res) => { const training = load().find((item) => item.id === req.params.id && (origin(item) === 'admin' || item.organizationId === req.accessUser.organizationId)); if (!training) return res.status(404).json({ ok: false, error: 'Treinamento nao encontrado.' }); res.json({ ok: true, training: { id: training.id, title: training.title }, viewers: await metricsFor(training, req.accessUser.organizationId) }); });

router.get('/api/admin/training-center', requireAdmin, (req, res) => res.json({ ok: true, trainings: load().filter((item) => origin(item) === 'admin') }));
router.post('/api/admin/training-center', requireAdmin, async (req, res, next) => { try { const items = load(), now = new Date().toISOString(), item = payload(req.body); Object.assign(item, { id: crypto.randomUUID(), ownerType: 'admin', createdAt: now, updatedAt: now }); items.push(item); save(items); const users = await usersFor(supabase.from('users').select('id,name,email,role,organization_id,organizations!users_organization_id_fkey(name)').in('role', ['supervisor', 'broker']).eq('status', 'active')); let emailDelivery; try { emailDelivery = await notify(item, users, 'Lungo Corretores'); } catch (error) { emailDelivery = { recipients: users.length, sent: 0, failed: users.length, error: error.message }; } res.status(201).json({ ok: true, training: item, emailDelivery }); } catch (error) { next(error); } });
router.patch('/api/admin/training-center/:id', requireAdmin, (req, res, next) => { try { const items = load(), index = items.findIndex((item) => item.id === req.params.id && origin(item) === 'admin'); if (index < 0) return res.status(404).json({ ok: false, error: 'Treinamento nao encontrado.' }); items[index] = { ...payload(req.body, items[index]), ownerType: 'admin', updatedAt: new Date().toISOString() }; save(items); res.json({ ok: true, training: items[index] }); } catch (error) { next(error); } });
router.delete('/api/admin/training-center/:id', requireAdmin, (req, res) => { const items = load(), next = items.filter((item) => !(item.id === req.params.id && origin(item) === 'admin')); if (next.length === items.length) return res.status(404).json({ ok: false, error: 'Treinamento nao encontrado.' }); save(next); res.json({ ok: true }); });
router.get('/api/admin/training-center/:id/metrics', requireAdmin, async (req, res) => { const training = load().find((item) => item.id === req.params.id && origin(item) === 'admin'); if (!training) return res.status(404).json({ ok: false, error: 'Treinamento nao encontrado.' }); res.json({ ok: true, training: { id: training.id, title: training.title }, viewers: await metricsFor(training) }); });

module.exports = router;
